### PR TITLE
Use the same default flags as stdlib’s log I just think this is what most Go developers will expect; I know I did.

### PR DESCRIPTION
**Pull request by aviflax**
@timehop/backend please :eyes: thanks!

### CODE REVIEW

**Comment by brunodecarvalho** [comment]
For historical reference, the default was none as we were running this in containers that already provided these flags (foreman and Heroku.)

**Comment by aviflax** [comment]
@brunodecarvalho good to know, thanks! While that’s understandable, I do feel that the intuitive thing is to use the same default as the stdlib’s `log` package. How does that sound?

**Comment by brunodecarvalho** [comment]
I'm cool with this. Ship it :+1:

**Comment by aviflax** [comment]
Cool, thanks!

**Pull request merged**
